[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "whiteout"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "SQLAlchemy>=2.0.52",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.5",
    "python-dotenv==1.2.3",
]
authors = [{ name = "Noise The White", email = "me@noisethewhite.dev" }]
description = "Write description later."
readme = "README.md"

[project.urls]
Repository = "https://github.com/noisethewhite/whiteout.git"

[project.scripts]
whiteout = "whiteout.cli:main"

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "basedpyright>=1.39.10",
    "pytest>=9.1.1",
]
